# Remember to keep sync with MODULE.bazel
blazerod_version = "0.0.6"
mod_version = "0.0.6"
game_version = "1.21.8"
fabric_api_version = "0.129.0+1.21.8"
fabric_api_version_modrinth = "X2hTodix"
fabric_language_kotlin_version = "1.13.5+kotlin.2.2.10"
fabric_language_kotlin_version_modrinth = "Y91MRWtG"
neoforge_version = "21.8.36"
home_page = "https://github.com/fifth-light/ArmorStand"
sources_page = "https://github.com/fifth-light/ArmorStand"
issue_tracker = "https://github.com/fifth-light/ArmorStand/issues"
license = "LGPL-3.0-or-later"
